import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
  return (    
    <>
      <Head>
        <title>Egg Chakra UI</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Hello Next.js</h1>
    </>
  )
}

export default Home
